config/routes.rb
Rails.application.routes.draw do
  namespace :azul do
    post "authenticate_user_ajax"
    post "send_to_carrier"
    get  "get_awbs"
  end

  post  "azul/:shipment_id/get_awb",        to: "azul#get_awb"
end

app/models/carrier/azul.rb
class Carrier::Azul < Carrier
  class << self

    def shipping_methods
      {
        'Standart': ['id_base']
      }
    end

    def general_settings
      ['Email','Senha','CpfCnpj']
    end

    def tracking_url
      "http://www.azulcargo.com.br/Rastreio.aspx?n={tracking}&tipoAwb=Nacional"
    end

    def get_tracking_number(shipment)
      check_invoice_xml(shipment)
      get_awb(shipment)
    end

    def check_for_updates
      shipments.each do |shipment|
        get_updates(shipment)
      end
    end

    def get_awb(shipment)
      xml = Nokogiri::XML(shipment.invoice_xml)
      str = xml.at_css('infNFe').attribute("Id").try(:content)
      nfe_key = str[3..-1]
      account = shipment.account
      check_authentication(account)
      token = account.azul_settings['token']
      response = request.get("WebAPI_EdiAzulCargo/api/Ocorrencias/Consultar?token=#{token}&ChaveNFE=#{nfe_key}")
      check_response(response)
      response.body.dig("Value",0,"Awb")
    end

    def get_delivery_updates(shipment)
      check_authentication(shipment.account)
      check_tracking_number(shipment)
      token = shipment.account.azul_settings['token']
      response = request.get("WebAPI_EdiAzulCargo/api/Ocorrencias/Consultar?Token=#{token}&AWB=#{shipment.tracking_number}")
      check_response(response)
      events = response.body.dig("Value",0,"Ocorrencias")
      events.each do |event|
        history = shipment.histories.find_by(description:event["Descricao"])
        next if history.present?
        description = "#{event["Descricao"]} - #{event["UnidadeMunicipio"]}, #{event["UnidadeUF"]}"
        shipment.histories.create(
          description: description,
          city: event["UnidadeMunicipio"],
          state: event["UnidadeUF"],
          date: event["DataHora"],
          changed_by: 'Azul',
          category: 'carrier'
        )
      end
    end

    def check_response(response)
      if response.body["HasErrors"]
        raise Exception.new("Azul - #{response.body["ErrorText"]}")
      elsif response.body["Value"].empty?
        raise Exception.new("Ainda não há informações de rastreamento. Tente mais tarde.")
      end
    end

    def check_tracking_number(shipment)
      raise Exception.new("Azul - Este envio não tem um código de rastreio (AWB)") if shipment.tracking_number.blank?
    end

    def send_to_carrier(shipments)
      response = []
      shipments.each do |shipment|
        begin
          account = shipment.account
          check_authentication(account)
          check_invoice_xml(shipment)
          encoded_xml = Base64.strict_encode64(shipment.invoice_xml)
          faraday_response = send_to_azul(account,encoded_xml)
          message = faraday_response.body["HasErrors"] ? faraday_response.body["ErrorText"] : faraday_response.body["Value"]
          shipment.update(sent_to_carrier:true) unless faraday_response.body["HasErrors"]
          response << {
            shipment: shipment,
            success: shipment.sent_to_carrier,
            message: message
          }
        rescue  Exception => e
          response << {
            shipment: shipment,
            success: shipment.sent_to_carrier,
            message: e.message
          }
        end
      end
      response
    end

    def authenticate_user(account, user, password, cpf_cnpj)
      credentials = {
          "Email" => user,
          "Senha" => password,
          "CpfCnpj" => cpf_cnpj
      }
      response    = request.post("WebAPI_EdiAzulCargo/api/Autenticacao/ValidarUsuarioPortalClienteEdi", credentials)
      if response.body["HasErrors"]
        raise Exception.new("Azul - Authentication Error: #{response.body["ErrorText"]}")
      else
        token       = response.body["Value"]
        account.azul_settings['token'] = token
        account.azul_settings['token_expire_date'] = DateTime.now + 7.hours
        account.save
      end
      response
    end

    private

    def check_authentication(account)
      settings          = account.azul_settings
      token_expire_date = settings['token_expire_date'].try(:to_datetime)
      user     = settings['general']['Email']
      password = settings['general']['Senha']
      cpf_cnpj = settings['general']['CpfCnpj']
      authenticate_user(account, user, password, cpf_cnpj) if !token_expire_date || token_expire_date < DateTime.now
    end

    def check_invoice_xml(shipment)
      raise Exception.new("Azul - É necessário o XML da nota fiscal") if shipment.invoice_xml.blank?
    end

    def send_to_azul(account, encoded_xml)
      token = account.azul_settings['token']
      body  = {
        "xml": encoded_xml,
      }
      response = request.post("WebAPI_EdiAzulCargo/api/NFe/Enviar?token=#{token}",body)
    end

    def request
      Faraday.new(url: "http://hmg.onlineapp.com.br/") do |conn|
        conn.request :json
        conn.response :json, :content_type => /\bjson$/
        conn.adapter Faraday.default_adapter
      end
    end

  end
end

app/controllers/azul_controller.rb
class AzulController < ApplicationController
  skip_before_action :verify_authenticity_token

  def authenticate_user_ajax
    begin
      account  = current_company.accounts.find(params["account"])
      user     = params["email"]
      password = params["password"]
      cpf_cnpj = params["cpf_cnpj"]
      response = Carrier::Azul.authenticate_user(account, user, password, cpf_cnpj)
      render json: response.body.to_json
    rescue Exception => e
      render json: e.message.to_json
    end
  end

  def send_to_carrier # Button in settings to send shipments to azul
    carrier   = Carrier::Azul
    account   = Account.find(params["account"])
    shipments = carrier.shipment.ready_to_ship.where(account:account)
    begin
      shipments.each do |shipment|
        carrier.send_to_carrier(shipment)
        shipment.update(sent_to_carrier:true)
      end
      flash[:success] = 'Todos pedidos foram sincronizados'
    rescue Exception => e
      flash[:error] = e.message
    end
    redirect_to edit_carrier_path(carrier.id)
  end

  def get_awbs
    @results = []
    Carrier::Azul.shipments.where(tracking_number:nil,account:params[:account]).each do |shipment|
      begin
        awb = Carrier::Azul.get_awb(shipment)
        shipment.update(tracking_number: awb)
        message = "Rastreio atualizado: AWB #{awb}"
      rescue Exception => e
        message = e.message
      end
      result_hash = {
        shipment: shipment,
        message: message
      }
      @results << result_hash
    end
  end

end

app/views/azul/get_awbs.html.erb
<% content_for :subheader_title do %>
Atualizando AWB dos pedidos que ainda estão sem rastreio...
<% end %>


<div class="kt-portlet">
  <div class="kt-portlet__head">
    <div class="kt-portlet__head-label">
      <h3 class="kt-portlet__head-title">
        Envios
      </h3>
    </div>
  </div>

  <div class="kt-portlet__body">
    <div class="kt-portlet__content">
      <table class="table table-hover table-head-noborder">
        <thead>
          <tr>
            <th>Envio</th>
            <th>Mensagem</th>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |result| %>
          <tr>
            <td><%= link_to "#{result[:shipment].shipment_number} - #{result[:shipment].full_name}", shipment_path(result[:shipment]), class: "kt-link" %> </td>
            <td><%= result[:message] %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/carriers/_azul_settings.html.erb
<% content_for :subheader_title do %>
<%= @carrier.display_name %>
<% end %>
<% content_for :subheader_toolbar do %>

<div class="kt-subheader__toolbar">
  <div class="kt-subheader__wrapper">
    <ul class="nav nav-tabs nav-tabs-bold nav-tabs-line nav-tabs-line-brand m-0" role="tablist">
      <% @accounts.each do |account| %>
      <li class="nav-item">
        <a class="nav-link p-1" data-toggle="tab" href="#kt_portlet_tabs_1_<%= account.id %>_content" role="tab">
          <%= account.name %>
        </a>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="tab-content">
  <% @accounts.each do |account| %>
  <% settings = account.send(@carrier.settings_field) %>
  <div class="tab-pane" id="kt_portlet_tabs_1_<%= account.id %>_content" role="tabpanel">

    <%= form_for :settings, url: "/accounts/#{account.id}/update_carrier_settings" do |f| %>
    <%= hidden_field_tag 'account_id', account.id %>

    <div class="row">
      <div class="col-md-6">
        <div class="kt-portlet">
          <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
              <h3 class="kt-portlet__head-title">
                Configurações de acesso
              </h3>
            </div>
          </div>

          <div class="kt-portlet__body">
            <%= hidden_field_tag 'carrier_id', @carrier.id %>
            <%= f.fields_for 'general' do |ff| %>
            <div class="row">
              <% @carrier.settings['general'].each do |setting| %>
              <div class="col-md-4">
                <div class="form-group">
                  <%= ff.label setting %>
                  <%= ff.text_field setting, value: settings.dig('general',setting), class:'form-control' %>
                </div>
              </div>
              <% end %>
            </div>
            <div class="row">
              <div class="col-md-2">
                <%= link_to "javascript:;", class:"connect" do %>
                <button type="button" class="btn btn-sm btn-default"><i class="la la-refresh"></i> Conectar</button>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>


          <div class="kt-portlet__foot">
            <div class="kt-form__actions">
              <%= f.submit "Salvar", class:"btn btn-primary" %>
              <%= link_to 'Voltar', :back, class:"btn btn-secondary", style: "background-color:#ffffff"  %>
            </div>
          </div>

        </div>
      </div>

      <div class="col-md-6">
        <div class="kt-portlet">
          <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
              <h3 class="kt-portlet__head-title">
                Sincronização de pedidos
              </h3>
            </div>
          </div>

          <div class="kt-portlet__body" kt-hidden-height="163" style="">
            <div class="kt-portlet__content">
              <p>Enviar todos os pedidos com status "pronto para envio" para a Azul Cargo</p>
              <%= link_to "Enviar", azul_send_to_carrier_path(account:account), class: "btn btn-secondary", method:'post' %>
            </div>
          </div>
        </div>
        <div class="kt-portlet">
          <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
              <h3 class="kt-portlet__head-title">
                Obter rastreios
              </h3>
            </div>
          </div>

          <div class="kt-portlet__body" kt-hidden-height="163" style="">
            <div class="kt-portlet__content">
              <p>Checar AWB dos pedidos que não tem rastreio definido</p>
              <%= link_to "Atualizar", azul_get_awbs_path(account:account), class: "btn btn-secondary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>

  </div>
  <% end %>
</div>

<script>
$('.connect').click(function(){
  form  = $(this).parents('form')
  email    = form.find('input[name="settings[general][Email]"]').val();
  password = form.find('input[name="settings[general][Senha]"]').val();
  cpf_cnpj = form.find('input[name="settings[general][CpfCnpj]"]').val();
  account  = form.find('input[name="account_id"]').val();
  data = {
    email:    email,
    password: password,
    cpf_cnpj: cpf_cnpj,
    account:  account
  }
  var request = $.ajax({
    url: "<%= azul_authenticate_user_ajax_url %>",
    method: "POST",
    dataType: 'json',
    data: data
  });
  request.done(function( msg ) {
    if ( msg["HasErrors"] == false ) {
      alert("Conectado com sucesso");
    }
  });
  request.fail(function( jqXHR, textStatus ) {
    alert( "Request failed: " + textStatus );
  });
})
</script>

<script>
$('.nav-link').first().addClass('active');
$('.tab-pane').first().addClass('active');
</script>

app/views/shipments/_azul_label.html.erb
<% shipment = package.shipment %>
<% total_packages = shipment.packages.size %>
<style>
.label {
  font-size: 20px;
  font-family: helvetica;
  padding: 25px;
  line-height: 1.3;
}
.address {
  list-style: none;
  padding: 0;
  margin: 0;
}

.text-center {
  text-align: center;
}
.mt20 {
  margin-top: 20px;
}

.package {
  text-align: right;
}

.sender-address li {
  font-size: 17px;
}

h4 {
  margin-bottom: 10px;
  margin-top: 10px;
}

.space-between {
  display: flex;
  justify-content: space-between;
}
</style>

<div class="label">
  <div class="space-between">
    <div>
      <%= shipment.carrier.display_name %>
    </div>
    <div>
      Pacote <%= shipment.packages.index(package) + 1 %>/<%= total_packages %><br>
    </div>
  </div>

  <div class="package">
    Pacote <%= shipment.packages.index(package) + 1 %>/<%= total_packages %><br>
  </div>

  <% if shipment.tracking_number.present? %>
  <div class='text-center mt20'>
    <%= shipment.tracking_number %><br>
    <%= image_tag(Barby::Code128.new(shipment.tracking_number).to_image(xdim:2).to_data_url) %>
  </div>
  <% end %>

  <hr>

  <h4>DESTINATÁRIO</h4>
  <ul class="address">
    <li><%= shipment.first_name %> <%= shipment.last_name %></li>
    <li><%= shipment.street %>, <%= shipment.number %></li>
    <li><%= "#{shipment.complement}," if shipment.complement.present? %> <%= shipment.neighborhood %></li>
    <li><strong><%= shipment.zip %></strong> <%= shipment.city %> / <%= shipment.state %></li>

    <% if shipment.zip.present? %>
    <%= image_tag(Barby::Code128.new(shipment.zip.delete("^0-9")).to_image(xdim:2).to_data_url) %>
    <% end %>
  </ul>

  <hr>

  <h4>REMETENTE</h4>
  <% account = shipment.account %>
  <ul class="address sender-address">
    <li><%= account.name %></li>
    <li><%= account.street %>, <%= account.number %></li>
    <li><%= "#{account.complement}," if account.complement.present? %> <%= account.neighborhood %></li>
    <li><strong><%= account.zip %></strong> <%= account.city %> / <%= account.state %></li>
  </ul>
</div>